// 工程化高级/26-vite-vite基本使用/src/react/App.jsx
import React, { useState } from 'react'

function AppReact() {
    const [count, setCount] = useState(0)
    return (
        <div className='app'>
            <h2>React 计数器：{count}</h2>
            <button onClick={e => setCount(count + 1)}>+1</button>
        </div>
    )
}

export default AppReact

// 工程化高级/25-roullup-rollup业务打包/src/vue/App.vue
<template>
    <div class="app">
        <h2>App 计数器： {{ count }}</h2>
        <button @click="increment">+1</button>
    </div>
</template>

<script setup>
    import { ref } from 'vue'

    const count = ref(100)

    function increment() {
        count.value++
    }
</script>

<style scoped>

</style>
